language: node_js
node_js:
- 5.0
script: ./ci/travis_deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "4901db4b206c"
  - COMMIT_AUTHOR_EMAIL: "frontpressbot@gmail.com"
cache:
  directories:
    - node_modules
